config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :options

  resources :vehicles

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.is_admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/option.rb
class Option < ActiveRecord::Base
  has_many :vehicle_options
  has_many :vehicles, through: :vehicle_options

  OPTION_TYPES = [
    "Tires",
    "Transmission",
    "Monitors",
    "Rims",
    "Audio",
    "Tint",
    "Neon Lights",
    "Wing Size",
    "Turbo Power",
    "NOS",
    "Lift Kit",
    "Flux Capacitor",
    "Hydraulics"
  ]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_admin?
    is_admin
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :vehicle_options
  has_many :options, through: :vehicle_options

  MAKE = [
    "Toyota",
    "Lotus",
    "Blotus",
    "Billy Bob Truck",
    "Delorean",
    "Datsun",
    "Batmobile",
    "Ferrari",
    "Honda"
  ]

  AVAILABLE_STATES = [
    ["Sell", "sold"],
    ["Buy", "new"]
  ]

  scope :search_vehicles, -> search { where( "vehicle_model like ? OR make like ? OR year like ? OR color like ? OR cost like ? OR year like ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" ) }

  include Workflow
  workflow do
    state :new do
      event :sell_car, transitions_to: :sold
    end

    state :sold do
      event :buy_car, transitions_to: :new
    end
  end
end

app/models/vehicle_option.rb
class VehicleOption < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :option
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    authorize! :read, Option
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
    authorize! :read, Option
  end

  # GET /options/new
  def new
    authorize! :manage, Option
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
    authorize! :manage, Option
  end

  # POST /options
  # POST /options.json
  def create
    authorize! :manage, Option
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    authorize! :manage, Option
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    authorize! :manage, Option
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:option_type, :name, :cost, :markup)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    authorize! :read, Vehicle
    @vehicles = if params[:q]
      Vehicle.search_vehicles params[:q]
    else
      Vehicle.all
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    authorize! :read, Vehicle
  end

  # GET /vehicles/new
  def new
    authorize! :manage, Vehicle
    @vehicle = Vehicle.new
    @options = Option.all
  end

  # GET /vehicles/1/edit
  def edit
    authorize! :manage, Vehicle
    @options = Option.all
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    authorize! :manage, Vehicle
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    authorize! :manage, Vehicle
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    authorize! :manage, Vehicle
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(
        :make,
        :vehicle_model,
        :year,
        :color,
        :cost,
        :markup,
        {option_ids: [] },
        :workflow_state 
      )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_tab(link_controller)
    "active" if params[:controller] == link_controller

    # if params[:controller] == link_controller
    #   "active" 
    # end
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
  def display_availability(vehicle)
    if vehicle.workflow_state == 'new'
      'Available'
    else
      'Sold'
    end
  end

  def  availability_class(vehicle)
    if vehicle.workflow_state == 'new'
      'success'
    else
      'warning'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.haml
%ul.nav.nav-pills.pull-right
  %li{ class: active_tab("welcome") }
    = link_to "Home", root_path
  %li{ class: active_tab("vehicles") }
    = link_to "Karz", vehicles_path
  %li{ class: active_tab("options") }
    = link_to "Optiiiinz", options_path
  - if current_user
    %li
      = link_to "Logout", destroy_user_session_path, method: :delete
  - else
    %li{ class: active_tab("devise/sessions") }
      = link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %link{:href => "../../assets/ico/favicon.ico", :rel => "shortcut icon"}
    / Bootstrap core CSS
    %title VehicleApplication
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / Just for debugging purposes. Don't actually copy this line!
    /[if lt IE 9] <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
    %script{src:"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
    %script{src:"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"}
  %body
    .container
      .header
        = render 'layouts/navbar'
        %h3.text-muted Kevin's Bodee Shop

      %p.notice= notice
      %p.alert= alert
      = yield
      .footer
        %p &copy; Company 2014
    / /container
    /
      Bootstrap core JavaScript
      \==================================================
    / Placed at the end of the document so the pages load faster

app/views/options/_form.html.haml
= form_for @option do |f|
  - if @option.errors.any?
    #error_explanation
      %h2= "#{pluralize(@option.errors.count, "error")} prohibited this option from being saved:"
      %ul
        - @option.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :option_type
    = f.select :option_type, options_for_select(Option::OPTION_TYPES, @option.option_type), include_blank: "--- Select ---"
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :cost
    = f.text_field :cost
  .field
    = f.label :markup
    = f.text_field :markup
  .actions
    = f.submit 'Save', class: "btn btn-default"

app/views/options/edit.html.haml
%h1 Editing option

= render 'form'

= link_to 'Show', @option
\|
= link_to 'Back', options_path

app/views/options/index.html.haml
%h1 Listing options

%table.table.table-hover
  %tr
    %th Option type
    %th Name
    %th Cost
    - if can? :manage, Option
      %th Markup
    %th
    %th
    %th

  - @options.each do |option|
    %tr
      %td= option.option_type
      %td= option.name
      %td= option.cost
      - if can? :manage, Option
        %td= option.markup
      %td= link_to 'Show', option
      %td= link_to 'Edit', edit_option_path(option) if can? :manage, Option
      %td= link_to 'Destroy', option, :method => :delete, :data => { :confirm => 'Are you sure?' } if can? :manage, Option

%br

= link_to 'New Option', new_option_path if can? :manage, Option

app/views/options/new.html.haml
%h1 New option

= render 'form'

= link_to 'Back', options_path

app/views/options/show.html.haml
%p#notice= notice

%p
  %b Option type:
  = @option.option_type
%p
  %b Name:
  = @option.name
%p
  %b Cost:
  = @option.cost
%p
  %b Markup:
  = @option.markup
- if can? :manage, Option
  = link_to 'Edit', edit_option_path(@option)
  \|
= link_to 'Back', options_path

app/views/vehicles/_form.html.haml
= form_for @vehicle, html: {role: "form", class: "form-horizontal"} do |f|
  - if @vehicle.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vehicle.errors.count, "error")} prohibited this vehicle from being saved:"
      %ul
        - @vehicle.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :make, class: "col-lg-2"
    .col-lg-10
      = f.select :make, options_for_select(Vehicle::MAKE, @vehicle.make), include_blank: "--- Select ---"
  .form-group
    = f.label :vehicle_model
    = f.text_field :vehicle_model
  .form-group
    = f.label :year
    = f.select :year, options_for_select((Time.zone.now.year - 100)..(Time.zone.now.year + 1), @vehicle.year || Time.zone.now.year )
  .form-group
    = f.label :color
    = f.text_field :color
  .form-group
    = f.label :cost
    = f.text_field :cost
  .form-group
    = f.label :markup
    = f.text_field :markup
  .form-group
    - @options.each do |option|
      = check_box_tag "vehicle[option_ids][]", option.id, @vehicle.options.map(&:id).include?(option.id), id: "option_#{option.id}"
      = label_tag "option_#{option.id}", option.name
  = f.submit 'Save', class: "btn btn-default"

app/views/vehicles/_vehicles.html.haml
%table.table.table-hover.vehicles
  %tr
    %th Make
    %th Model
    %th Year
    %th Color
    %th Cost
    - if can? :manage, Vehicle
      %th Markup
    %th Availability
    %th
    %th
    %th
    %th

  - @vehicles.each do |vehicle|
    %tr{class: "#{availability_class(vehicle)} vehicle_#{vehicle.id}" }
      %td= vehicle.make
      %td= vehicle.vehicle_model
      %td= vehicle.year
      %td= vehicle.color
      %td= vehicle.cost
      %td= vehicle.markup if can? :manage, Vehicle
      %td.workflow_state= display_availability(vehicle)
      %td= link_to 'Show', vehicle
      %td= link_to 'Edit', edit_vehicle_path(vehicle) if can? :manage, Vehicle
      %td= link_to 'Destroy', vehicle, :method => :delete, :data => { :confirm => 'Are you sure?' } if can? :manage, Vehicle
      - if can? :manage, Vehicle
        %td
          = select_tag "workflow[#{vehicle.id}]", options_for_select(Vehicle::AVAILABLE_STATES), prompt: "--- Select ---", update_url: vehicle_path(vehicle)

app/views/vehicles/edit.html.haml
%h1 Editing vehicle

= render 'form'

= link_to 'Show', @vehicle
\|
= link_to 'Back', vehicles_path

app/views/vehicles/index.html.haml
%h1 Listing vehicles
= form_tag vehicles_path, method: :get, remote: true
= text_field_tag 'q', '', placeholder: "Search Vehicles"
= submit_tag "Search", class: "btn btn-primary"
%br
%br
= render "vehicles"
%br

= link_to 'New Vehicle', new_vehicle_path if can? :manage, Vehicle

app/views/vehicles/index.js.haml
$(".vehicles").replaceWith(
'#{escape_javascript(render(partial: "vehicles/vehicles"))}'
)

app/views/vehicles/new.html.haml
%h1 New vehicle

= render 'form'

= link_to 'Back', vehicles_path

app/views/vehicles/show.html.haml
%p#notice= notice

%p
  %b Make:
  = @vehicle.make
%p
  %b Vehicle model:
  = @vehicle.vehicle_model
%p
  %b Year:
  = @vehicle.year
%p
  %b Color:
  = @vehicle.color
%p
  %b Cost:
  = @vehicle.cost
%p
  %b Markup:
  = @vehicle.markup
%p
  %b Options:
  - @vehicle.options.each do |option|
    = option.name
    %br
- if can? :manage, Vehicle
  = link_to 'Edit', edit_vehicle_path(@vehicle)
  \|
= link_to 'Back', vehicles_path

app/views/vehicles/update.js.haml
$(".vehicle_#{@vehicle.id}").toggleClass("success");
$(".vehicle_#{@vehicle.id}").toggleClass("warning");
$(".vehicle_#{@vehicle.id} td.workflow_state").html("#{display_availability(@vehicle)}")

app/views/welcome/index.html.haml
.jumbotron
  %h1 Buy Some Karz Plz KThx.
  %p.lead
    Plz buy sum KARZ frum uz plz. We r eetin' ramin. We ned sum educashinz.
  %p
    = link_to "Buy sum karz tdaay", vehicles_path, class: "btn btn-lg btn-success", role: "button"
.row.marketing